export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME';
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const PREFILL_USER_INFO = 'PREFILL_USER_INFO';
export const VINIT_READY = 'VINIT_READY';
